src/app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
 */

Route::group(array('prefix' => 'api'), function() {
    $namespace = 'Api';
//    Route::controller('product', $namespace . '\ProductController');
});

/*
| ROUTE STRUCTURE FOR DOCOMO
| Required routes will be created first
| Need to update extra routes when develop
*/

Route::pattern('id', '[0-9]+');

Route::get('manage/', ['as' => 'admin.home', 'uses' => 'Admin\HomeController@index', 'after' => 'header.all']);
Route::post('manage/', ['as' => 'admin.login', 'uses' => 'Admin\HomeController@login', 'after' => 'header.all']);

Route::group(['prefix' => 'manage', 'namespace' => 'Admin', 'before' => 'auth', 'after' => 'header.all'], function(){
    // ADMIN_01 and ADMIN_02

    Route::get('/logout', ['as' => 'admin.logOut', 'uses' => 'HomeController@logOut']);

        // ADMIN_03 - ADMIN_06
    Route::post('/question/create',        ['as' => 'manage.question.store',    'uses' => 'QuestionController@store']);
    Route::put('/question/{id}/edit',      ['as' => 'manage.question.update',   'uses' => 'QuestionController@update']);
    Route::get('/question/{id}/complete/{message_type?}',      ['as' => 'manage.question.complete',   'uses' => 'QuestionController@complete']);
    Route::get('/question/{id}/result', ['as' => 'manage.question.result'             , 'uses' => 'QuestionController@result']);
    Route::get('/question/{id}/csv/{attr}/{device?}', ['as' => 'manage.question.csv'             , 'uses' => 'QuestionController@csv']);
    Route::post('/question/{id}/result', ['as' => 'manage.question.result'             , 'uses' => 'QuestionController@updateColumn']);
    Route::put('/question/{id}/result', ['as' => 'manage.question.result'             , 'uses' => 'QuestionController@updateColumn']);
    Route::resource('question', 'QuestionController', ['except' => ['show', 'store', 'update']]);
    Route::post('/question',        ['as' => 'manage.question.search',    'uses' => 'QuestionController@search']);

    Route::get('/question/dump',                     ['as' => 'manage.question.dump', 'uses' => 'QuestionController@downloadDump', 'before' => 'auth.manage:summary']);

    Route::group(['before' => 'auth.manage:column'], function () {
        Route::get('/column',                   ['as' => 'manage.column.index', 'uses' => 'QuestionController@searchColumn']);
        Route::post('/column',                   ['as' => 'manage.column.search', 'uses' => 'QuestionController@searchColumn']);
    });

    //ADMIN_07 - ADMIN_10
    Route::group(['before' => 'auth.manage:feature'], function() {
        Route::post('/feature/create'      , ['as' => 'admin.feature.store'              , 'uses' => 'FeatureController@store']);
        Route::post('/feature/confirm'     , ['as' => 'admin.feature.confirm'             , 'uses' => 'FeatureController@confirm']);
        Route::put('/feature/{id}/edit'   , ['as' => 'admin.feature.update'                , 'uses' => 'FeatureController@update']);
        Route::resource('feature', 'FeatureController', ['except' => ['show', 'store', 'update']]);
    });

    //ADMIN_11
    Route::group(['before' => 'auth.manage:pickup'], function() {
        Route::get('/pickup/create/{id}',      ['as' => 'manage.pickup.create',   'uses' => 'PickupController@create']);
        Route::post('/pickup/create/{id}',      ['as' => 'manage.pickup.store',   'uses' => 'PickupController@store']);
        Route::put('/pickup/{id}/edit'   , ['as' => 'admin.pickup.update'                , 'uses' => 'PickupController@update']);
        Route::resource('pickup', 'PickupController', ['except' => ['show', 'create', 'store', 'update']]);
    });

    //ADMIN_11 - ADMIN_13
    Route::group(['before' => 'auth.manage:attention'], function() {
        Route::post('/attention/create',      ['as' => 'manage.attention.store',    'uses' => 'AttentionController@store']);
        Route::put('/attention/{id}/edit',    ['as' => 'manage.attention.update',   'uses' => 'AttentionController@update']);
        Route::resource('attention', 'AttentionController', ['except' => ['store', 'show', 'update']]);
    });

        //ADMIN_14 - ADMIN_16
    Route::group(['before' => 'auth.manage:genre'], function() {
        Route::put('/genre',               ['as' => 'manage.genre.sort',    'uses' => 'GenreController@sort']);
        Route::post('/genre/create',        ['as' => 'manage.genre.store',    'uses' => 'GenreController@store']);
        Route::put('/genre/{id}/edit',      ['as' => 'manage.genre.update',   'uses' => 'GenreController@update']);
        Route::resource('genre', 'GenreController', ['except' => ['store', 'show', 'update', 'destroy']]);
    });

    Route::get('/keyword/pick/{max?}',  ['as' => 'manage.keyword.pick',     'uses' => 'KeywordController@pick']);
        //ADMIN_17 - ADMIN_19
    Route::group(['before' => 'auth.manage:keyword'], function() {
        Route::post('/keyword/create',      ['as' => 'manage.keyword.store',    'uses' => 'KeywordController@store']);
        Route::put('/keyword/{id}/edit',    ['as' => 'manage.keyword.update',   'uses' => 'KeywordController@update']);
        Route::resource('keyword', 'KeywordController', ['except' => ['store', 'show', 'update', 'destroy']]);
    });

        //ADMIN_23 - ADMIN_25
    Route::group(['before' => 'auth.manage:account', 'after' => 'header.all'], function() {
        Route::post('/account/create',      ['as' => 'manage.account.store',    'uses' => 'AccountController@store']);
        Route::put('/account/{id}/edit',    ['as' => 'manage.account.update',   'uses' => 'AccountController@update']);
        Route::resource('account', 'AccountController', ['except' => ['store', 'show', 'update', 'destroy']]);
    });
        //ADMIN_05 - ADMIN_05_3
    Route::group(['before' => 'auth.manage:notice'], function() {
        Route::post('/notice/create',       ['as' => 'manage.notice.store',         'uses' => 'NoticeController@store']);
        Route::put('/notice/{id}/edit',     ['as' => 'manage.notice.update',        'uses' => 'NoticeController@update']);
        Route::post('/notice/confirm',      ['as' => 'manage.notice.confirm',       'uses' => 'NoticeController@confirm']);
        Route::resource('notice', 'NoticeController', ['except' => ['store', 'show', 'update']]);
    });

    Route::group(['before' => 'auth.manage:summary'], function () {
        Route::get('/summary/daily/vote',   ['as' => 'manage.summary.daily_vote',   'uses' => 'SummaryController@dailyVote']);
        Route::post('/summary/daily/vote',  ['as' => 'manage.summary.daily_vote',   'uses' => 'SummaryController@dailyVote']);

        Route::get('/summary/vote/ranking',     ['as' => 'manage.summary.vote_ranking',     'uses' => 'SummaryController@voteRanking']);
        Route::post('/summary/vote/ranking',    ['as' => 'manage.summary.vote_ranking',     'uses' => 'SummaryController@voteRanking']);

        Route::get('/summary/vote/genre',     ['as' => 'manage.summary.vote_genre',     'uses' => 'SummaryController@voteGenre']);
        Route::post('/summary/vote/genre',    ['as' => 'manage.summary.vote_genre',     'uses' => 'SummaryController@voteGenre']);

        Route::get('/summary/vote/profile',     ['as' => 'manage.summary.vote_profile',     'uses' => 'SummaryController@voteProfile']);
        Route::post('/summary/vote/profile',    ['as' => 'manage.summary.vote_profile',     'uses' => 'SummaryController@voteProfile']);

        Route::get('/summary/daily/profile',    ['as' => 'manage.summary.daily_profile',    'uses' => 'SummaryController@dailyProfile']);
        Route::post('/summary/daily/profile',   ['as' => 'manage.summary.daily_profile',    'uses' => 'SummaryController@dailyProfile']);

        Route::get('/summary/profile',  ['as' => 'manage.summary.profile',  'uses' => 'SummaryController@profile']);
        Route::post('/summary/profile', ['as' => 'manage.summary.profile',  'uses' => 'SummaryController@profile']);

        Route::get('/summary/chmod_log',    ['as' => 'manage.summary.chmod',        'uses' => 'SummaryController@chmodLog']);
    });



    Route::group([], function () {
        // 管理画面ができる前提でgroup化
        Route::get('/upload/create',                    ['as' => 'manage.upload.create',      'uses' => 'UploadController@create']);
        Route::post('/upload/store',                    ['as' => 'manage.upload.store',      'uses' => 'UploadController@store']);
    });

});


Route::group(['namespace' => 'Front', 'before' => 'allow.device', 'after' => 'header.fp|header.all'], function(){

    // USER_SP_01
    Route::get('/'                            , ['as' => 'home.top'                , 'uses' => 'HomeController@index']);//ok
    Route::post('/home/getAcceptingProfileQuestion'   , ['as' => 'home.getAcceptingProfileQuestion'    , 'uses' => 'HomeController@getAcceptingProfileQuestion']);//ok
    Route::post('/home/getAnnouncedProfileQuestion'   , ['as' => 'home.getAnnouncedProfileQuestion'    , 'uses' => 'HomeController@getAnnouncedProfileQuestion']);//ok

    // USER_SP_02
    Route::get( '/{parent_genre_name}/{child_genre_name}/entry/{id}'                , ['as' => 'entry.show',         'uses' => 'EntryController@show']);
    Route::put( '/{parent_genre_name}/{child_genre_name}/entry/{id}'                , ['as' => 'entry.set.attribute',         'uses' => 'EntryController@updateUser']);
    Route::post('/{parent_genre_name}/{child_genre_name}/entry/{id}/{choice_id?}'   , ['as' => 'entry.answer',       'uses' => 'EntryController@answer']);

    // USER_SP_03

src/app/controllers/admin/FeatureController.php
<?php
namespace Admin;

use docomo\Models\Features\Feature;


class FeatureController extends \BaseController
{
    
    /**
     *
     */
    public function __construct()
    {
        
    }
    
    /**
     * List Features
     *
     * @return View list Features
     */
    public function index()
    {

        \Session::forget(FEATURE);
        return \View::make('admin.feature.index', ['feature_list' => Feature::getList()]);
    }
    
    /**
     * Create feature
     *
     * @return View create feature
     */
    public function create()
    {
        $feature = \Session::get(FEATURE);
        if (is_null($feature)) {
            $feature = new Feature;
        } else {
            $feature = unserialize($feature);
        }

        if (!\Session::pull(FEATURE . '_confirm', false)) {
            \Session::forget(FEATURE);
            $feature = new Feature;
        }
        $feature->question_ids = trim($feature->question_ids, ',');
        return \View::make('admin.feature.create', compact('feature'));
    }
    
    /**
     * [confirm View confirm form feature]
     * @return [View] [View confirm form feature]
     */
    public function confirm()
    {
        $feature = \Session::pull(FEATURE);
        if (is_null($feature)) {
            $feature = new Feature;
        } else {
            $feature = unserialize($feature);
        }

        $feature = Feature::fillWithModify($feature->id, $feature->thumbnail);
        \Session::put(FEATURE, serialize($feature));
        if ($feature->confirmValidate()) {
            \Session::put(FEATURE . '_confirm', true);

            return \View::make('admin.feature.confirm', compact('feature'));
        }
        else
        {
            $errors = $feature->error_message;

            return \View::make((isset($feature->id)) ? 'admin.feature.edit' : 'admin.feature.create', compact('feature', 'errors'));
        }
    }
    
    /**
     * Deatail feature
     *
     * @param  [int] $id [id of feature]
     * @return View detail feature
     */
    public function edit($id)
    {
        $feature = \Session::pull(FEATURE);
        if (is_null($feature)) {
            $feature = Feature::details()->find($id);
        } else {
            $feature = unserialize($feature);
        }
        if ($feature->id != $id) {
            $feature = Feature::details()->find($id);
        }
        \Session::put(FEATURE, serialize($feature));

        return \View::make('admin.feature.edit', compact('feature'));
    }
    
    /**
     * Create feature
     *
     * @return insert feature in database
     */
    public function store()
    {

        return $this->saveFeature('create');
    }
    
    /**
     * Edit feature
     *
     * @param  [int] $id [Id of feature]
     * @return [Redirect]     [update success feature and redirect to list feature]
     */
    public function update($id)
    {

        return $this->saveFeature('edit');
    }
    
    /**
     * [delete Delete Feature]
     * @param  [int] $id [id of feature]
     * @return [View]     [delete feature and redirect to list feature]
     */
    public function destroy($id)
    {
        $feature = Feature::find($id);
        $feature->delete();
        
        return \Redirect::route('manage.feature.index');
    }

    private function saveFeature($mode)
    {

        $feature = \Session::pull(FEATURE);
        if (is_null($feature)) {
            $feature = new Feature;
        } else {
            $feature = unserialize($feature);
        }

        $feature->saveFile();
        unset(Feature::$rules['from']);
        unset(Feature::$rules['to']);

        $questionIdList = $feature->questionIdList;
        $feature = $feature->cloneObject();

        if ($feature->save())
        {
            Feature::saveList($feature->id, $questionIdList);
            return \Redirect::route('manage.feature.index');
        }
        else
        {
            $errors = $feature->errors();

            return \View::make('admin.feature.' . $mode, compact('feature', 'errors'));
        }

    }
}

src/app/controllers/front/FeatureController.php
<?php namespace Front;

use docomo\Models\Features\Feature;

class FeatureController extends \BaseController {

    public function __construct(){

    }

    public function detailFeature($id)
    {
        $feature = Feature::whereRaw('`from` < NOW()')->find($id);
        if (!isset($feature)) {
            return \Redirect::route('feature');
        }
        $past_features = Feature::getPastCount();
        return $this->renderView(\View::make('front.feature.detail', compact('feature', 'past_features')));
    }

    public function listFeature()
    {
        return $this->renderView(\View::make('front.feature.list'));
    }
}

src/app/views/admin/feature/confirm.blade.php
@extends('layouts.admin_in')
@section('head')
<link rel="stylesheet" href="{{ url('common/admin/css/jquery-ui-1.8.23.custom.css') }}" type="text/css" />
<link rel="stylesheet" href="{{ url('common/front/css/feature.css') }}" type="text/css" />
<script type="text/javascript" src=" {{ url('common/admin/js/jquery-ui-1.8.23.custom.min.js') }}"></script>
<script type="text/javascript" src=" {{ url('common/admin/js/jquery.ui.datepicker-ja.js') }}"></script>
@stop
@section('script')
<script type="text/javascript">
$(window).load(function(){
    var confirmMsg = '{{ (empty($feature->id)) ? C_REGISTRATION : C_UPDATE }}';
    $('.entryBtn').click(function(){
        return confirm(confirmMsg);
    });
    $('#reEditBtn').click(function(){
        window.location = '{{ (is_null($feature->id)) ? '/manage/feature/create' : '/manage/feature/' . $feature->id . '/edit' }}';
    });
});
</script>
@stop
@section('style')
<style>
div.imageBox{
    display:inline-block;
    background-color:#ccc;
    color:#333;
    text-align:center;
    position:relative;
}
div.imageBox span{
    padding:10px;
    display:inline-block;
}
.noticeBox{

}
.noticeTitle{
    background-color:#666;
    padding:5px 10px;
    color:#fff;
    margin-bottom:10px;
    font-size:16px;
}
ul.voteList{
    border-top:1px dotted #ccc;
}
ul.voteList li{
    border-bottom:1px dotted #ccc;
    background:url({{ url('common/admin/images/arrow.png') }}) no-repeat right center;
}
ul.voteList li a{
    padding:10px 20px 10px 0px;
    display:block;
    text-decoration:none;
    color:#333;
}
ul.voteList li a span.genre{
    display:inline-block;
    background-color:#333;
    color:#fff;
    font-size:12px;
    padding:2px 5px;
}
ul.voteList li a span.voteTit{
    display:block;
    padding:2px 0px;
}
ul.voteList li a span.voteDate{
    display:block;
    padding:2px 0px;
    color:#999;
    font-size:10px;
}   
</style>
@stop
@section('content')
<h2>TOPページ特集枠データ作成</h2>
{{ Form::model($feature, (is_null($feature->id)) ? ['url' => 'manage/feature/create', 'method' => 'post'] : ['url' => 'manage/feature/' . $feature->id . '/edit', 'method' => 'put']) }}
<p>イメージ</p>
<div style="width:320px;margin-left:auto;margin-right:auto;">
    @include('layouts.elements.displays.feature_box')
</div>
<br /><br />
<p>期間：{{ $feature->from }}&nbsp;&nbsp;～&nbsp;&nbsp;{{ $feature->to }}</p>
<div class="tcenter m-margint">
<button type="button" name="commit" class="commitBtn" id="reEditBtn">編集しなおす</button>
<button type="submit" name="commit" class="commitBtn entryBtn">登録</button>
</div>

{{ Form::close() }}
@stop

src/app/views/admin/feature/create.blade.php
@extends('layouts.admin_in')

@section('content')
<h2>TOPページ特集枠データ作成</h2>
@include('admin.feature.form', ['feature' => $feature])

@stop

src/app/views/admin/feature/edit.blade.php
@extends('layouts.admin_in')

@section('content')
<h2>TOPページ特集枠データ作成</h2>
@include('admin.feature.form', ['feature' => $feature])

@stop

src/app/views/admin/feature/form.blade.php
@section('head')
<link rel="stylesheet" href="{{ url('common/admin/css/jquery-ui-1.8.23.custom.css') }}" type="text/css" />
<script type="text/javascript" src=" {{ url('common/admin/js/jquery-ui-1.8.23.custom.min.js') }}"></script>
<script type="text/javascript" src=" {{ url('common/admin/js/jquery.ui.datepicker-ja.js') }}"></script>
@stop
@section('script')
<script type="text/javascript">
$(window).load(function(){
    
    //日付ピッカー
    $("input[name='from_date']").datepicker({
        dateFormat: 'yymmdd'
    });
    //日付ピッカー
    $("input[name='to_date']").datepicker({
        dateFormat: 'yymmdd'
    });
});
</script>
@stop

@include('admin.share.errors', ['errorList' => $errors])
{{ Form::model($feature, ['url' => '/manage/feature/confirm', 'method' => 'post', 'files' => true]) }}
    <p>特集枠表示内容</p>
    <table class="formTable">
    <tr>
        <th>タイトル<span class="require">（必須）</span></th>
        <td>{{ Form::text('title', $feature->title, ['class' => 'xx-large']) }}</td>
    </tr>
    <tr>
        <th>サムネイル<br />(横144px推奨)50KB以内</th>
        <td>@include('layouts.elements.displays.file_uploader', ['uploader_id' => 'thumbnail_file', 'db_file' => $feature->thumbnail])</td>
    </tr>
    <tr>
        <th>メッセージ<br />HTML可</th>
        <td>{{ Form::textarea('message', $feature->message, ['class' => 'xx-large', 'rows' => 10]) }}</td>
    </tr>
    <tr>
        <th>期間<span class="require">（必須）</span></th>
        <td>
            {{ Form::dateTimeControl('from', $feature->from) }}
        <br />
        <br />
        ～<br />
        <br />
            {{ Form::dateTimeControl('to', $feature->to) }}
        </td>
    </tr>
    <tr>
    <th>特集一覧に表示</th>
    <td>
        <label>
           {{ Form::checkbox('is_view_list', null, $feature->is_view_list) }} 特集一覧に表示する
        </label>
    </td>
    </tr>

    </table>
    <br />
    <p>リスト</p>
    <table class="formTable">
        <tr class="typeChoice">
            <th>アンケートID</th>
            <td>{{ Form::text('question_ids', implode(',', $feature->getQuestionIdList()), ['class' => 'xx-large']) }}<p>
                    ※IDをカンマ区切りで入れてください
                    <a href="#" target="_blank" onclick="window.open('{{ route('manage.question.index') }}', 'searchwindow', 'width=800, height=600, menubar=no, toolbar=no, scrollbars=yes');return false;">別ウィンドウで検索を開く</a></p></td>
        </tr>
    <tr>
        <th>コラム特集か？</th>
        <td>
            <label>{{ Form::checkbox('is_feature_column', null, $feature->is_feature_column) }} 遷移先でコラムを開く</label>
        </td>
    </tr>
    </table>
    <div class="tcenter m-margint">
        <button type="submit" name="commit" class="commitBtn">確認</button>
    </div>
{{ Form::close() }}

src/app/views/admin/feature/index.blade.php
@extends('layouts.admin_in')

@section('javascript')
    $(window).load(function(){
        $('.delete').click(function(e){
            return confirm('{{ C_DELETE }}');
        });
    });
@stop

@section('content')
<h2>TOPページ特集枠データ一覧</h2>
<table class="list">
    <tr>
        <th>ID</th>
        <th>タイトル</th>
        <th>コラムフラグ</th>
        <th style="width:90px;">開始</th>
        <th style="width:90px;">終了</th>
        <th>一覧表示フラグ</th>
        <th>削除</th>
    </tr>
    @foreach ($feature_list as $feature)
    <tr class="{{ ($feature->isEnd()) ? 'expiration' : '' }}">
        <td>{{ $feature->id }}</td>
        <td>{{ link_to_route('manage.feature.edit', $feature->title, $feature->id) }}</td>
        <td>{{ ($feature->is_feature_column) ? L_COLUMN : '' }}</td>
        <td>{{ date('Y-m-d H:i', strtotime($feature->from)) }}</td>
        <td>{{ date('Y-m-d H:i', strtotime($feature->to)) }}</td>
        <td>{{ ($feature->is_view_list) ? L_VISIBLE : '' }}</td>
        <td>
            {{ Form::open(['url' => 'manage/feature/' . $feature->id, 'method' => 'delete']) }}
                <button type="submit" class="naviBtn delete">削除</button>
            {{ Form::close() }}
        </td>
    </tr>
    @endforeach
</table>
@stop