src/app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
 */

Route::group(array('prefix' => 'api'), function() {
    $namespace = 'Api';
//    Route::controller('product', $namespace . '\ProductController');
});

/*
| ROUTE STRUCTURE FOR DOCOMO
| Required routes will be created first
| Need to update extra routes when develop
*/

Route::pattern('id', '[0-9]+');

Route::get('manage/', ['as' => 'admin.home', 'uses' => 'Admin\HomeController@index', 'after' => 'header.all']);
Route::post('manage/', ['as' => 'admin.login', 'uses' => 'Admin\HomeController@login', 'after' => 'header.all']);

Route::group(['prefix' => 'manage', 'namespace' => 'Admin', 'before' => 'auth', 'after' => 'header.all'], function(){
    // ADMIN_01 and ADMIN_02

    Route::get('/logout', ['as' => 'admin.logOut', 'uses' => 'HomeController@logOut']);

        // ADMIN_03 - ADMIN_06
    Route::post('/question/create',        ['as' => 'manage.question.store',    'uses' => 'QuestionController@store']);
    Route::put('/question/{id}/edit',      ['as' => 'manage.question.update',   'uses' => 'QuestionController@update']);
    Route::get('/question/{id}/complete/{message_type?}',      ['as' => 'manage.question.complete',   'uses' => 'QuestionController@complete']);
    Route::get('/question/{id}/result', ['as' => 'manage.question.result'             , 'uses' => 'QuestionController@result']);
    Route::get('/question/{id}/csv/{attr}/{device?}', ['as' => 'manage.question.csv'             , 'uses' => 'QuestionController@csv']);
    Route::post('/question/{id}/result', ['as' => 'manage.question.result'             , 'uses' => 'QuestionController@updateColumn']);
    Route::put('/question/{id}/result', ['as' => 'manage.question.result'             , 'uses' => 'QuestionController@updateColumn']);
    Route::resource('question', 'QuestionController', ['except' => ['show', 'store', 'update']]);
    Route::post('/question',        ['as' => 'manage.question.search',    'uses' => 'QuestionController@search']);

    Route::get('/question/dump',                     ['as' => 'manage.question.dump', 'uses' => 'QuestionController@downloadDump', 'before' => 'auth.manage:summary']);

    Route::group(['before' => 'auth.manage:column'], function () {
        Route::get('/column',                   ['as' => 'manage.column.index', 'uses' => 'QuestionController@searchColumn']);
        Route::post('/column',                   ['as' => 'manage.column.search', 'uses' => 'QuestionController@searchColumn']);
    });

    //ADMIN_07 - ADMIN_10
    Route::group(['before' => 'auth.manage:feature'], function() {
        Route::post('/feature/create'      , ['as' => 'admin.feature.store'              , 'uses' => 'FeatureController@store']);
        Route::post('/feature/confirm'     , ['as' => 'admin.feature.confirm'             , 'uses' => 'FeatureController@confirm']);
        Route::put('/feature/{id}/edit'   , ['as' => 'admin.feature.update'                , 'uses' => 'FeatureController@update']);
        Route::resource('feature', 'FeatureController', ['except' => ['show', 'store', 'update']]);
    });

    //ADMIN_11
    Route::group(['before' => 'auth.manage:pickup'], function() {
        Route::get('/pickup/create/{id}',      ['as' => 'manage.pickup.create',   'uses' => 'PickupController@create']);
        Route::post('/pickup/create/{id}',      ['as' => 'manage.pickup.store',   'uses' => 'PickupController@store']);
        Route::put('/pickup/{id}/edit'   , ['as' => 'admin.pickup.update'                , 'uses' => 'PickupController@update']);
        Route::resource('pickup', 'PickupController', ['except' => ['show', 'create', 'store', 'update']]);
    });

    //ADMIN_11 - ADMIN_13
    Route::group(['before' => 'auth.manage:attention'], function() {
        Route::post('/attention/create',      ['as' => 'manage.attention.store',    'uses' => 'AttentionController@store']);
        Route::put('/attention/{id}/edit',    ['as' => 'manage.attention.update',   'uses' => 'AttentionController@update']);
        Route::resource('attention', 'AttentionController', ['except' => ['store', 'show', 'update']]);
    });

        //ADMIN_14 - ADMIN_16
    Route::group(['before' => 'auth.manage:genre'], function() {
        Route::put('/genre',               ['as' => 'manage.genre.sort',    'uses' => 'GenreController@sort']);
        Route::post('/genre/create',        ['as' => 'manage.genre.store',    'uses' => 'GenreController@store']);
        Route::put('/genre/{id}/edit',      ['as' => 'manage.genre.update',   'uses' => 'GenreController@update']);
        Route::resource('genre', 'GenreController', ['except' => ['store', 'show', 'update', 'destroy']]);
    });

    Route::get('/keyword/pick/{max?}',  ['as' => 'manage.keyword.pick',     'uses' => 'KeywordController@pick']);
        //ADMIN_17 - ADMIN_19
    Route::group(['before' => 'auth.manage:keyword'], function() {
        Route::post('/keyword/create',      ['as' => 'manage.keyword.store',    'uses' => 'KeywordController@store']);
        Route::put('/keyword/{id}/edit',    ['as' => 'manage.keyword.update',   'uses' => 'KeywordController@update']);
        Route::resource('keyword', 'KeywordController', ['except' => ['store', 'show', 'update', 'destroy']]);
    });

        //ADMIN_23 - ADMIN_25
    Route::group(['before' => 'auth.manage:account', 'after' => 'header.all'], function() {
        Route::post('/account/create',      ['as' => 'manage.account.store',    'uses' => 'AccountController@store']);
        Route::put('/account/{id}/edit',    ['as' => 'manage.account.update',   'uses' => 'AccountController@update']);
        Route::resource('account', 'AccountController', ['except' => ['store', 'show', 'update', 'destroy']]);
    });
        //ADMIN_05 - ADMIN_05_3
    Route::group(['before' => 'auth.manage:notice'], function() {
        Route::post('/notice/create',       ['as' => 'manage.notice.store',         'uses' => 'NoticeController@store']);
        Route::put('/notice/{id}/edit',     ['as' => 'manage.notice.update',        'uses' => 'NoticeController@update']);
        Route::post('/notice/confirm',      ['as' => 'manage.notice.confirm',       'uses' => 'NoticeController@confirm']);
        Route::resource('notice', 'NoticeController', ['except' => ['store', 'show', 'update']]);
    });

    Route::group(['before' => 'auth.manage:summary'], function () {
        Route::get('/summary/daily/vote',   ['as' => 'manage.summary.daily_vote',   'uses' => 'SummaryController@dailyVote']);
        Route::post('/summary/daily/vote',  ['as' => 'manage.summary.daily_vote',   'uses' => 'SummaryController@dailyVote']);

        Route::get('/summary/vote/ranking',     ['as' => 'manage.summary.vote_ranking',     'uses' => 'SummaryController@voteRanking']);
        Route::post('/summary/vote/ranking',    ['as' => 'manage.summary.vote_ranking',     'uses' => 'SummaryController@voteRanking']);

        Route::get('/summary/vote/genre',     ['as' => 'manage.summary.vote_genre',     'uses' => 'SummaryController@voteGenre']);
        Route::post('/summary/vote/genre',    ['as' => 'manage.summary.vote_genre',     'uses' => 'SummaryController@voteGenre']);

        Route::get('/summary/vote/profile',     ['as' => 'manage.summary.vote_profile',     'uses' => 'SummaryController@voteProfile']);
        Route::post('/summary/vote/profile',    ['as' => 'manage.summary.vote_profile',     'uses' => 'SummaryController@voteProfile']);

        Route::get('/summary/daily/profile',    ['as' => 'manage.summary.daily_profile',    'uses' => 'SummaryController@dailyProfile']);
        Route::post('/summary/daily/profile',   ['as' => 'manage.summary.daily_profile',    'uses' => 'SummaryController@dailyProfile']);

        Route::get('/summary/profile',  ['as' => 'manage.summary.profile',  'uses' => 'SummaryController@profile']);
        Route::post('/summary/profile', ['as' => 'manage.summary.profile',  'uses' => 'SummaryController@profile']);

        Route::get('/summary/chmod_log',    ['as' => 'manage.summary.chmod',        'uses' => 'SummaryController@chmodLog']);
    });



    Route::group([], function () {
        // 管理画面ができる前提でgroup化
        Route::get('/upload/create',                    ['as' => 'manage.upload.create',      'uses' => 'UploadController@create']);
        Route::post('/upload/store',                    ['as' => 'manage.upload.store',      'uses' => 'UploadController@store']);
    });

});


Route::group(['namespace' => 'Front', 'before' => 'allow.device', 'after' => 'header.fp|header.all'], function(){

    // USER_SP_01
    Route::get('/'                            , ['as' => 'home.top'                , 'uses' => 'HomeController@index']);//ok
    Route::post('/home/getAcceptingProfileQuestion'   , ['as' => 'home.getAcceptingProfileQuestion'    , 'uses' => 'HomeController@getAcceptingProfileQuestion']);//ok
    Route::post('/home/getAnnouncedProfileQuestion'   , ['as' => 'home.getAnnouncedProfileQuestion'    , 'uses' => 'HomeController@getAnnouncedProfileQuestion']);//ok

    // USER_SP_02
    Route::get( '/{parent_genre_name}/{child_genre_name}/entry/{id}'                , ['as' => 'entry.show',         'uses' => 'EntryController@show']);
    Route::put( '/{parent_genre_name}/{child_genre_name}/entry/{id}'                , ['as' => 'entry.set.attribute',         'uses' => 'EntryController@updateUser']);
    Route::post('/{parent_genre_name}/{child_genre_name}/entry/{id}/{choice_id?}'   , ['as' => 'entry.answer',       'uses' => 'EntryController@answer']);

    // USER_SP_03

src/app/views/admin/home.blade.php
@extends('layouts.admin')

@section('content')

<h2>メインメニュー</h2>
<div class="menuArea clearfix">
	<div class="leftBlock">
		<h3>アンケート管理</h3>
		<ul>
			<li><a href="{{ route('manage.question.create') }}">アンケート新規投稿</a></li>
			<li><a href="{{ route('manage.question.index') }}">アンケート検索・修正・削除</a></li>
			<li><a href="{{ route('manage.question.index', ['status' => QUESTION_STATUS_REQUEST_APPROVE]) }}">承認申請中（{{ $counts[QUESTION_STATUS_REQUEST_APPROVE] }}）</a></li>
			<li><a href="{{ route('manage.question.index', ['status' => QUESTION_STATUS_REJECT]) }}">差戻し（{{ $counts[QUESTION_STATUS_REJECT] }}）</a></li>
@if(Auth::user()->havePermission('is_manage_column'))
            <li><a href="{{ route('manage.column.index') }}">コラム検索・編集</a></li>
@endif
@if(Auth::user()->havePermission('is_manage_summary'))
            <li><a href="{{ route('manage.question.dump') }}">全アンケートダウンロード</a></li>
@endif
		</ul>
		@if(Auth::user()->havePermission('is_manage_feature'))
		<h3>TOPページ特集枠管理</h3>
		<ul>
			<li><a href="{{ route('manage.feature.create') }}">特集枠データ作成</a></li>
			<li><a href="{{ route('manage.feature.index') }}">特集枠一覧・修正・削除</a></li>
		</ul>
		@endif
		@if(Auth::user()->havePermission('is_manage_attention'))
		<h3>TOPページ注目キーワード管理</h3>
		<ul>
			<li><a href="{{ route('manage.attention.create') }}">注目キーワードデータ作成</a></li>
			<li><a href="{{ route('manage.attention.index') }}">注目キーワード一覧・修正・削除</a></li>
		</ul>
		@endif
		@if(Auth::user()->havePermission('is_manage_pickup'))
			<h3>TOPページピックアップアンケート管理</h3>
			<ul>
				<li><a href="{{ route('manage.pickup.index') }}">ピックアップ一覧・修正・削除</a></li>
			</ul>
		@endif
	</div><!--/leftBlock-->
	<div class="rightBlock">
		@if(Auth::user()->havePermission('is_manage_genre'))
		<h3>ジャンル管理</h3>
		<ul>
			<li><a href="{{ route('manage.genre.index') }}">ジャンル一覧・登録・修正</a></li>
		</ul>
		@endif
		@if(Auth::user()->havePermission('is_manage_keyword'))
		<h3>キーワード管理</h3>
		<ul>
			<li><a href="{{ route('manage.keyword.index') }}">キーワード一覧・登録・修正</a></li>
		</ul>
		@endif

		@if(Auth::user()->havePermission('is_manage_account'))
		<h3>アカウント管理</h3>
		<ul>
			<li><a href="{{ route('manage.account.index') }}">アカウント一覧・登録・修正</a></li>
		</ul>
		@endif
		@if(Auth::user()->havePermission('is_manage_notice'))
		<h3>お知らせ管理</h3>
		<ul>
			<li><a href="{{ route('manage.notice.index') }}">お知らせ一覧・登録・修正・削除</a></li>
		</ul>
		@endif
        @if(true || Auth::user()->havePermission('is_manage_notice'))
            <h3>画像管理</h3>
            <ul>
                <li><a href="{{ route('manage.upload.create') }}">画像ファイルアップロード</a></li>
            </ul>
        @endif
		@if(Auth::user()->havePermission('is_manage_summary'))
		<h3>投票・プロフィール集計</h3>
		<ul>
			<li><a href="{{ route('manage.summary.daily_vote') }}">日別得票数</a></li>
            <li><a href="{{ route('manage.summary.vote_genre') }}">ジャンル別得票数</a></li>
            <li><a href="{{ route('manage.summary.vote_profile') }}">プロフィール別得票数</a></li>
			<li><a href="{{ route('manage.summary.vote_ranking') }}">得票数ランキング</a></li>
			<li><a href="{{ route('manage.summary.daily_profile') }}">日別プロフィール登録</a></li>
			<li><a href="{{ route('manage.summary.profile') }}">プロフィール登録累計</a></li>
		</ul>
		@endif
	</div><!--/rightBlock-->
</div><!--/menuArea-->

@stop

src/app/views/admin/login.blade.php
<!DOCTYPE HTML>
<html lang="ja">
    <head>
@include('layouts.elements.partials.header') 

<style>
#loginBox{
    width:500px;
    border:1px solid #ccc;
    -webkit-border-radius:5px;
    border-radius:5px;
    margin:150px auto;
    background-color:#fff;
    padding:20px;
}
#loginBox .loginTit{
    font-size:20px;
    margin:20px 0px;
    text-align:center;
}
#loginBox dl{
    margin:20px auto;
    width:150px;
}
#loginBox dl dd{
    margin-bottom:10px;
}
</style>
</head>
<body>
{{ Form::open(["action"=>"Admin\HomeController@login", "id" => "form_login", 'autocomplete' => 'off']) }}
<div id="loginBox">
<p class="loginTit">みんなの声　管理画面</p>
@include('admin.share.errors', ['errorList' => $errors])
<dl>
@include('layouts.modal.modal')
<dt>ログインID</dt>
<dd><input type="text" name="login_id" value="" /></dd>
<dt>パスワード</dt>
<dd><input type="password" name="login_password" value="" autocomplete="off" /></dd>
</dl>

<p class="tcenter"><button type="submit" name="loginCommit" class="commitBtn">ログイン</button></p>
<!--/loginBox--></div>
{{ Form::close() }}
</body>
</html>