src/app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
 */

Route::group(array('prefix' => 'api'), function() {
    $namespace = 'Api';
//    Route::controller('product', $namespace . '\ProductController');
});

/*
| ROUTE STRUCTURE FOR DOCOMO
| Required routes will be created first
| Need to update extra routes when develop
*/

Route::pattern('id', '[0-9]+');

Route::get('manage/', ['as' => 'admin.home', 'uses' => 'Admin\HomeController@index', 'after' => 'header.all']);
Route::post('manage/', ['as' => 'admin.login', 'uses' => 'Admin\HomeController@login', 'after' => 'header.all']);

Route::group(['prefix' => 'manage', 'namespace' => 'Admin', 'before' => 'auth', 'after' => 'header.all'], function(){
    // ADMIN_01 and ADMIN_02

    Route::get('/logout', ['as' => 'admin.logOut', 'uses' => 'HomeController@logOut']);

        // ADMIN_03 - ADMIN_06
    Route::post('/question/create',        ['as' => 'manage.question.store',    'uses' => 'QuestionController@store']);
    Route::put('/question/{id}/edit',      ['as' => 'manage.question.update',   'uses' => 'QuestionController@update']);
    Route::get('/question/{id}/complete/{message_type?}',      ['as' => 'manage.question.complete',   'uses' => 'QuestionController@complete']);
    Route::get('/question/{id}/result', ['as' => 'manage.question.result'             , 'uses' => 'QuestionController@result']);
    Route::get('/question/{id}/csv/{attr}/{device?}', ['as' => 'manage.question.csv'             , 'uses' => 'QuestionController@csv']);
    Route::post('/question/{id}/result', ['as' => 'manage.question.result'             , 'uses' => 'QuestionController@updateColumn']);
    Route::put('/question/{id}/result', ['as' => 'manage.question.result'             , 'uses' => 'QuestionController@updateColumn']);
    Route::resource('question', 'QuestionController', ['except' => ['show', 'store', 'update']]);
    Route::post('/question',        ['as' => 'manage.question.search',    'uses' => 'QuestionController@search']);

    Route::get('/question/dump',                     ['as' => 'manage.question.dump', 'uses' => 'QuestionController@downloadDump', 'before' => 'auth.manage:summary']);

    Route::group(['before' => 'auth.manage:column'], function () {
        Route::get('/column',                   ['as' => 'manage.column.index', 'uses' => 'QuestionController@searchColumn']);
        Route::post('/column',                   ['as' => 'manage.column.search', 'uses' => 'QuestionController@searchColumn']);
    });

    //ADMIN_07 - ADMIN_10
    Route::group(['before' => 'auth.manage:feature'], function() {
        Route::post('/feature/create'      , ['as' => 'admin.feature.store'              , 'uses' => 'FeatureController@store']);
        Route::post('/feature/confirm'     , ['as' => 'admin.feature.confirm'             , 'uses' => 'FeatureController@confirm']);
        Route::put('/feature/{id}/edit'   , ['as' => 'admin.feature.update'                , 'uses' => 'FeatureController@update']);
        Route::resource('feature', 'FeatureController', ['except' => ['show', 'store', 'update']]);
    });

    //ADMIN_11
    Route::group(['before' => 'auth.manage:pickup'], function() {
        Route::get('/pickup/create/{id}',      ['as' => 'manage.pickup.create',   'uses' => 'PickupController@create']);
        Route::post('/pickup/create/{id}',      ['as' => 'manage.pickup.store',   'uses' => 'PickupController@store']);
        Route::put('/pickup/{id}/edit'   , ['as' => 'admin.pickup.update'                , 'uses' => 'PickupController@update']);
        Route::resource('pickup', 'PickupController', ['except' => ['show', 'create', 'store', 'update']]);
    });

    //ADMIN_11 - ADMIN_13
    Route::group(['before' => 'auth.manage:attention'], function() {
        Route::post('/attention/create',      ['as' => 'manage.attention.store',    'uses' => 'AttentionController@store']);
        Route::put('/attention/{id}/edit',    ['as' => 'manage.attention.update',   'uses' => 'AttentionController@update']);
        Route::resource('attention', 'AttentionController', ['except' => ['store', 'show', 'update']]);
    });

        //ADMIN_14 - ADMIN_16
    Route::group(['before' => 'auth.manage:genre'], function() {
        Route::put('/genre',               ['as' => 'manage.genre.sort',    'uses' => 'GenreController@sort']);
        Route::post('/genre/create',        ['as' => 'manage.genre.store',    'uses' => 'GenreController@store']);
        Route::put('/genre/{id}/edit',      ['as' => 'manage.genre.update',   'uses' => 'GenreController@update']);
        Route::resource('genre', 'GenreController', ['except' => ['store', 'show', 'update', 'destroy']]);
    });

    Route::get('/keyword/pick/{max?}',  ['as' => 'manage.keyword.pick',     'uses' => 'KeywordController@pick']);
        //ADMIN_17 - ADMIN_19
    Route::group(['before' => 'auth.manage:keyword'], function() {
        Route::post('/keyword/create',      ['as' => 'manage.keyword.store',    'uses' => 'KeywordController@store']);
        Route::put('/keyword/{id}/edit',    ['as' => 'manage.keyword.update',   'uses' => 'KeywordController@update']);
        Route::resource('keyword', 'KeywordController', ['except' => ['store', 'show', 'update', 'destroy']]);
    });

        //ADMIN_23 - ADMIN_25
    Route::group(['before' => 'auth.manage:account', 'after' => 'header.all'], function() {
        Route::post('/account/create',      ['as' => 'manage.account.store',    'uses' => 'AccountController@store']);
        Route::put('/account/{id}/edit',    ['as' => 'manage.account.update',   'uses' => 'AccountController@update']);
        Route::resource('account', 'AccountController', ['except' => ['store', 'show', 'update', 'destroy']]);
    });
        //ADMIN_05 - ADMIN_05_3
    Route::group(['before' => 'auth.manage:notice'], function() {
        Route::post('/notice/create',       ['as' => 'manage.notice.store',         'uses' => 'NoticeController@store']);
        Route::put('/notice/{id}/edit',     ['as' => 'manage.notice.update',        'uses' => 'NoticeController@update']);
        Route::post('/notice/confirm',      ['as' => 'manage.notice.confirm',       'uses' => 'NoticeController@confirm']);
        Route::resource('notice', 'NoticeController', ['except' => ['store', 'show', 'update']]);
    });

    Route::group(['before' => 'auth.manage:summary'], function () {
        Route::get('/summary/daily/vote',   ['as' => 'manage.summary.daily_vote',   'uses' => 'SummaryController@dailyVote']);
        Route::post('/summary/daily/vote',  ['as' => 'manage.summary.daily_vote',   'uses' => 'SummaryController@dailyVote']);

        Route::get('/summary/vote/ranking',     ['as' => 'manage.summary.vote_ranking',     'uses' => 'SummaryController@voteRanking']);
        Route::post('/summary/vote/ranking',    ['as' => 'manage.summary.vote_ranking',     'uses' => 'SummaryController@voteRanking']);

        Route::get('/summary/vote/genre',     ['as' => 'manage.summary.vote_genre',     'uses' => 'SummaryController@voteGenre']);
        Route::post('/summary/vote/genre',    ['as' => 'manage.summary.vote_genre',     'uses' => 'SummaryController@voteGenre']);

        Route::get('/summary/vote/profile',     ['as' => 'manage.summary.vote_profile',     'uses' => 'SummaryController@voteProfile']);
        Route::post('/summary/vote/profile',    ['as' => 'manage.summary.vote_profile',     'uses' => 'SummaryController@voteProfile']);

        Route::get('/summary/daily/profile',    ['as' => 'manage.summary.daily_profile',    'uses' => 'SummaryController@dailyProfile']);
        Route::post('/summary/daily/profile',   ['as' => 'manage.summary.daily_profile',    'uses' => 'SummaryController@dailyProfile']);

        Route::get('/summary/profile',  ['as' => 'manage.summary.profile',  'uses' => 'SummaryController@profile']);
        Route::post('/summary/profile', ['as' => 'manage.summary.profile',  'uses' => 'SummaryController@profile']);

        Route::get('/summary/chmod_log',    ['as' => 'manage.summary.chmod',        'uses' => 'SummaryController@chmodLog']);
    });



    Route::group([], function () {
        // 管理画面ができる前提でgroup化
        Route::get('/upload/create',                    ['as' => 'manage.upload.create',      'uses' => 'UploadController@create']);
        Route::post('/upload/store',                    ['as' => 'manage.upload.store',      'uses' => 'UploadController@store']);
    });

});


Route::group(['namespace' => 'Front', 'before' => 'allow.device', 'after' => 'header.fp|header.all'], function(){

    // USER_SP_01
    Route::get('/'                            , ['as' => 'home.top'                , 'uses' => 'HomeController@index']);//ok
    Route::post('/home/getAcceptingProfileQuestion'   , ['as' => 'home.getAcceptingProfileQuestion'    , 'uses' => 'HomeController@getAcceptingProfileQuestion']);//ok
    Route::post('/home/getAnnouncedProfileQuestion'   , ['as' => 'home.getAnnouncedProfileQuestion'    , 'uses' => 'HomeController@getAnnouncedProfileQuestion']);//ok

    // USER_SP_02
    Route::get( '/{parent_genre_name}/{child_genre_name}/entry/{id}'                , ['as' => 'entry.show',         'uses' => 'EntryController@show']);
    Route::put( '/{parent_genre_name}/{child_genre_name}/entry/{id}'                , ['as' => 'entry.set.attribute',         'uses' => 'EntryController@updateUser']);
    Route::post('/{parent_genre_name}/{child_genre_name}/entry/{id}/{choice_id?}'   , ['as' => 'entry.answer',       'uses' => 'EntryController@answer']);

    // USER_SP_03

src/app/views/admin/question/column.blade.php
@extends('layouts.admin_in')

@section('head')
<link rel="stylesheet" href="{{ url('common/admin/css/jquery-ui-1.8.23.custom.css') }}" type="text/css" />
<script type="text/javascript" src=" {{ url('common/admin/js/jquery-ui-1.8.23.custom.min.js') }}"></script>
<script type="text/javascript" src=" {{ url('common/admin/js/jquery.ui.datepicker-ja.js') }}"></script>
@stop

@section('javascript')
$(window).load(function(){

    //日付ピッカー
    $("input[name='date_start']").datepicker({
        dateFormat: 'yymmdd'
    });
    //日付ピッカー
    $("input[name='date_end']").datepicker({
        dateFormat: 'yymmdd'
    });
});

function setOrder(column) {
    if ($('#sortColumn').val() == column) {
        if ($('#sortOrder').val() == 'asc') {
            $('#sortOrder').val('desc');
        } else {
            $('#sortOrder').val('asc');
        }
    } else {
        $('#sortColumn').val(column);
        $('#sortOrder').val('asc');
    }
    document.forms[0].submit();
    return false;
}

var keyword_name = $("#keyword_name").val();
$("#keywordList").text(keyword_name);

@stop

@section('style')
    <style type="text/css">
        .pagination li {
            display: inline;
            padding-left:4px;
            padding-right:4px;
        }
    </style>
@stop

@section('content')
<h2>コラム検索</h2>

{{ Form::model('conditions', ['method' => 'post']) }}
<input type="hidden" id="sortColumn" name="sortColumn" value="{{{ $conditions->sort_column }}}" />
<input type="hidden" id="sortOrder" name="sortOrder" value="{{{ $conditions->sort_order }}}" />
<table class="searchQuery">
    <tr>
        <th>コラム作成日</th>
        <td>
            {{ Form::text('date_start', $conditions->date_start) }}
            ～
            {{ Form::text('date_end', $conditions->date_end) }}
        </td>
    </tr>
@if (Auth::user()->havePermission('is_visible_register'))
    <tr>
        <th>コラム作成者</th>
        <td>
            {{ Form::selectByTable('register', $accounts, 'id', 'account_name', $conditions->register, true) }}
        </td>
    </tr>
@endif
    <tr>
        <th>表示フラグ</th>
        <td>
            {{ Form::select('visible', $visible, $conditions->visible) }}
        </td>
    </tr>
    <tr>
        <th>アンケートID絞り込み</th>
        <td>
            {{ Form::text('question_id', $conditions->question_id) }}
        </td>
    </tr>
    <tr>
        <th>タイトル・内容絞り込み</th>
        <td>
            {{ Form::text('search_text', $conditions->search_text) }}
        </td>
    </tr>
</table>
<p class="m-margin tcenter">
<button type="submit" class="commitBtn">検索</button>
</p>
@if (isset($columns))
<p class="m-margin">ヒット数：{{ number_format($columns->getTotal()) }}件</p>

<div id="order_tag"></div>
<table class="list">
    <tr>
        <th>ID</th>
        <th>タイトル</th>
        <th>概要</th>
        <th><a href="#" onclick="return setOrder('date');">コラム作成日{{ ($conditions->sort_column == 'date') ? (($conditions->sort_order == 'asc') ? '▲' : '▼') : '' }}</a></th>
        @if (Auth::user()->havePermission('is_visible_register'))
        <th>登録者</th>
        @endif
        <th>表示フラグ</th>
    </tr>
    @foreach ($columns as $column)
    <tr>
        <td>{{ $column->question_id }}</td>
        <td><a href="{{ route('manage.question.result', $column->question_id) }}#edit_column">{{{ $column->column_title }}}</a></td>
        <td>{{ $column->description }}</td>
        <td>{{ date('Y-m-d H:i', strtotime($column->view_create_datetime)) }}</td>
        @if (Auth::user()->havePermission('is_visible_register'))
        <td>{{{ docomo\Models\Accounts\Account::getAccountName($column->created_account_id) }}}</td>
        @endif
        <td>{{ ($column->is_visible) ? L_VISIBLE : L_HIDDEN }}</td>
    </tr>
    @endforeach
</table>
<br />
<div style="text-align: center;">
    @include('admin.question.pagination', ['paginator' => $columns, 'currentPage' => $columns->getCurrentPage(), 'lastPage' => $columns->getLastPage()])
</div>
@endif
{{ Form::close() }}

@stop

src/app/views/admin/question/complete.blade.php
@extends('layouts.admin_in')

@section('content')
    <h2>アンケート登録</h2>
    <div class="tcenter">

    @if (isset($message_type))
        @if ($status == QUESTION_STATUS_REJECT)
            <p class="l-margin">差し戻しました。</p>
            <p class="l-margin"><a href="{{ route('manage.question.edit', $question_id) }}">内容を確認する</a></p>
        @elseif ($status == QUESTION_STATUS_DRAFT)
            <p class="l-margin">下書きに戻しました。</p>
            <p class="l-margin"><a href="{{ route('manage.question.edit', $question_id) }}">再度編集する</a></p>
        @elseif ($status == QUESTION_STATUS_REQUEST_APPROVE)
            <p class="l-margin">上書き保存しました。</p>
            <p class="l-margin"><a href="{{ route('manage.question.edit', $question_id) }}">再度編集する</a></p>
        @elseif ($status == QUESTION_STATUS_WAITING)
            <p class="l-margin">更新しました。</p>
            <p class="l-margin"><a href="{{ route('manage.question.edit', $question_id) }}">内容を確認する</a></p>
        @elseif ($status == QUESTION_STATUS_FINISH)
            <p class="l-margin">更新しました。</p>
            <p class="l-margin"><a href="{{ route('manage.question.edit', $question_id) }}">内容を確認する</a></p>
        @elseif ($status == QUESTION_STATUS_READY)
            <p class="l-margin">更新しました。</p>
            <p class="l-margin"><a href="{{ route('manage.question.edit', $question_id) }}">内容を確認する</a></p>
        @endif
    @else
        @if ($status == QUESTION_STATUS_DRAFT || $status == QUESTION_STATUS_REJECT)
            <p class="l-margin">下書きとして保存しました。</p>
            <p class="l-margin"><a href="{{ route('manage.question.edit', $question_id) }}">再度編集する</a></p>
        @elseif ($status == QUESTION_STATUS_REQUEST_APPROVE)
            <p class="l-margin">承認申請しました。</p>
            <p class="l-margin"><a href="{{ route('manage.question.edit', $question_id) }}">内容を確認する</a></p>
        @elseif ($status == QUESTION_STATUS_WAITING)
            <p class="l-margin">受付準備中として反映しました。</p>
            <p class="l-margin"><a href="{{ route('manage.question.edit', $question_id) }}">内容を確認する</a></p>
        @elseif ($status == QUESTION_STATUS_READY)
            <p class="l-margin">受付中として反映しました。</p>
            <p class="l-margin"><a href="{{ route('manage.question.edit', $question_id) }}">内容を確認する</a></p>
        @elseif ($status == QUESTION_STATUS_FINISH)
            <p class="l-margin">受付終了として反映しました。</p>
            <p class="l-margin"><a href="{{ route('manage.question.edit', $question_id) }}">内容を確認する</a></p>
        @endif
    @endif

        <p class="l-margin"><a href="{{ route('manage.question.index') }}">アンケート一覧へ</a></p>
    </div>
@stop

src/app/views/admin/question/create.blade.php
@extends('layouts.admin_in')

@section('content')
<h2>アンケート登録</h2>
@include('admin.question.form', ['url' => 'manage/question/create','method' => 'post', 'status' => QUESTION_STATUS_CREATE, 'mode' => MODE_ALL_EDIT])

@stop

src/app/views/admin/question/edit.blade.php
@extends('layouts.admin_in')

@section('script')
<script type="text/javascript">
    $(window).load(function(){

        $('button.btnUpdateData').click(function(){
            if(confirm('{{ '' }}')){
                $('#status').val('{{''}}');
                $('#form').submit();
            }
        });

        function btnChangeStatus(obj, msg){
            obj.click(function(e) {
                return confirm(msg);
            });
        }

        btnChangeStatus($('.btnReject'), '{{ C_REJECT }}');
        btnChangeStatus($('.btnRequestCancel'), '{{ C_REQUEST_CANCEL }}');

        $('button.btnDeleteSurvey').click(function(){
            return (confirm('{{ C_DELETE }}'));
        });
    });
</script>
@stop

@section('content')
<h2>アンケート登録</h2>
@include('admin.question.view_parts.information')
<div class="tright">
    @include('admin.question.view_parts.header_buttons')
</div>
@include('admin.question.form', ['url' => 'manage/question/'. $question->id . '/edit', 'method' => 'put', 'mode' => $mode])
@stop

src/app/views/admin/question/edit_full.blade.php
@extends('layouts.admin_in')

@section('script')
    <script type="text/javascript">
    $(window).load(function(){
        $('button.btnUpdateData').click(function(){
            if(confirm('{{ '' }}')){
                $('#status').val('{{''}}');
                $('#form').submit();
            }
        });
    });
    </script>
@endsection

@section('content')
<h2>アンケート登録</h2>

@include('admin.question.form', ['url' => 'manage/question/'. $question->id . '/edit', 'method' => 'put', 'status' => QUESTION_STATUS_CREATE, 'mode' => $mode])
@stop

src/app/views/admin/question/index.blade.php
@extends('layouts.admin_in')

@section('head')
<link rel="stylesheet" href="{{ url('common/admin/css/jquery-ui-1.8.23.custom.css') }}" type="text/css" />
<script type="text/javascript" src=" {{ url('common/admin/js/jquery-ui-1.8.23.custom.min.js') }}"></script>
<script type="text/javascript" src=" {{ url('common/admin/js/jquery.ui.datepicker-ja.js') }}"></script>
@stop

@section('javascript')
$(window).load(function(){
    $('a#searchBtn').click(function(){
        $("table.list tr:gt(0)").hide();
        $("table.list tr[searchid="+$('select[name="genreSelect"]').val()+"]").show();
        return false;
    });

    //日付ピッカー
    $("input[name='date_from_start']").datepicker({
        dateFormat: 'yymmdd'
    });
    //日付ピッカー
    $("input[name='date_from_end']").datepicker({
        dateFormat: 'yymmdd'
    });
    //日付ピッカー
    $("input[name='date_to_start']").datepicker({
        dateFormat: 'yymmdd'
    });
    //日付ピッカー
    $("input[name='date_to_end']").datepicker({
        dateFormat: 'yymmdd'
    });
    $('#keywordListOpen').click(function(){
        window.open('{{route("manage.keyword.pick")}}/1', 'keywordwindow', 'width=400, height=300, menubar=no, toolbar=no, scrollbars=yes');
        return false;
    });

    $('#keywordClear a').click(function(){
        $('#keywordClear').hide();
        $("#keywordList").text('選択されていません');
        $('#keywordId').val('');
        $('#keyword_name').val('');
        return false;
    });
});

function setOrder(column) {
    if ($('#sortColumn').val() == column) {
        if ($('#sortOrder').val() == 'asc') {
            $('#sortOrder').val('desc');
        } else {
            $('#sortOrder').val('asc');
        }
    } else {
        $('#sortColumn').val(column);
        $('#sortOrder').val('asc');
    }
    document.forms[0].submit();
    return false;
}

var keyword_name = $("#keyword_name").val();
$("#keywordList").text(keyword_name);

@stop

@section('style')
    <style type="text/css">
        .pagination li {
            display: inline;
            padding-left:4px;
            padding-right:4px;
        }
    </style>
@stop

@section('content')
<h2>アンケート検索</h2>

{{ Form::model('conditions', ['method' => 'post']) }}
    <input type="hidden" id="sortColumn" name="sortColumn" value="{{{ $conditions->sort_column }}}" />
    <input type="hidden" id="sortOrder" name="sortOrder" value="{{{ $conditions->sort_order }}}" />
    <table class="searchQuery">
        <tr>
            <th>ジャンル</th>
            <td>
                {{ Form::selectGenre('genre', $genres, $conditions->genre) }}
            </td>
        </tr>
        <tr>
            <th>キーワード</th>
        <td>
            <a href="#" class="naviBtn" id="keywordListOpen">キーワードウィンドウを開く</a>
            <div id="keywordList">{{{ $conditions->isValidKeyword() ? $conditions->keyword_text : '選択されていません' }}}</div>
            <input id="keywordId" value="{{{ $conditions->isValidKeyword() ? $conditions->keyword : '' }}}" name="keyword_id" type="hidden">
            <input id="keyword_name" value="{{{ $conditions->isValidKeyword() ? $conditions->keyword_text : '' }}}" name="keyword_name" type="hidden">

            <p id="keywordClear" class="m-margint" style="{{ $conditions->isValidKeyword() ? '' : 'display:none;' }}"><a href="#" class="naviBtn">クリア</a></p>
        </td>
    </tr>
    <tr>
        <th>アンケート受付開始日</th>
        <td>
            {{ Form::text('date_from_start', $conditions->date_from_start) }}
            ～
            {{ Form::text('date_from_end', $conditions->date_from_end) }}
        </td>
    </tr>
    <tr>
        <th>アンケート受付終了日</th>
        <td>
            {{ Form::text('date_to_start', $conditions->date_to_start) }}
            ～
            {{ Form::text('date_to_end', $conditions->date_to_end) }}
        </td>
    </tr>
    <tr>
        <th>登録者</th>
        <td>
            {{ Form::selectByTable('register', $accounts, 'id', 'account_name', $conditions->register, true) }}
        </td>
    </tr>
    <tr>
        <th>ステータス</th>
        <td>
            {{ Form::select('status', $status, $conditions->status) }}

        </td>
    </tr>
    <tr>
        <th>コラム</th>
        <td>
            <label>
            {{ Form::checkbox('column_only', null, $conditions->column_only) }} コラムのみ</label>
        </td>
    </tr>
    <tr>
        <th>ID絞り込み</th>
        <td>
            {{ Form::text('question_id', $conditions->question_id) }}
        </td>
    </tr>
    <tr>
        <th>タイトル・選択肢絞り込み</th>
        <td>
            {{ Form::text('title_choice_text', $conditions->title_choice_text) }}
        </td>
    </tr>
    <tr>
        <th>表示</th>
        <td>
            {{ Form::select('viewable_type', $viewable, $conditions->viewable_type) }}
        </td>
    </tr>
</table>
<p class="m-margin tcenter">
<button type="submit" class="commitBtn">検索</button>
</p>
@if ($questions)
<p class="m-margin">ヒット数：{{ number_format($questions->getTotal()) }}件</p>

<div id="order_tag"></div>
<table class="list">
    <tr>
        <th>ID</th>
        <th>タイトル</th>
        <th>選択肢数</th>
        <th>小ジャンル名</th>
        <th><a href="#" onclick="return setOrder('from');">受付開始{{ ($conditions->sort_column == 'from') ? (($conditions->sort_order == 'asc') ? '▲' : '▼') : '' }}</a></th>
        <th><a href="#" onclick="return setOrder('to');">受付終了{{ ($conditions->sort_column == 'to') ? (($conditions->sort_order == 'asc') ? '▲' : '▼') : '' }}</a></th>
        <th>ステータス</th>
        <th>票数</th>
        @if (Auth::user()->havePermission('is_visible_register'))
        <th>登録者</th>
        @endif
        <th>表示</th>
        <th>結果</th>
    </tr>
    @foreach ($questions as $question)
    <tr>
        <td>{{ $question->id }}</td>
        <td>
            @if($question->isViewableEditPage())
                <a href="{{ route('manage.question.edit', $question->id) }}">{{{ $question->title }}}</a>
            @else
                {{{ $question->title }}}
            @endif
        </td>
        <td>{{ $question->getChoiceCount() }}</td>
        <td>{{{ $question->getChildGenreName() }}}</td>
        <td>{{ date('Y-m-d H:i', strtotime($question->vote_date_from)) }}</td>
        <td>{{ date('Y-m-d H:i', strtotime($question->vote_date_to)) }}</td>
        <td>{{ docomo\Models\Codes\QuestionStatus::$label[$question->status] }}</td>
        <td>{{ number_format($question->vote_count) }}</td>
        @if (Auth::user()->havePermission('is_visible_register'))
        <td>{{{ $question->getAccountName() }}}</td>
        @endif
        <td>{{ docomo\Models\Codes\QuestionViewable::$label[$question->viewable_type] }}</td>
        <td>{{ ($question->isViewableResult()) ? link_to_route('manage.question.result', '結果', $question->id) : '&nbsp;' }}</td>
    </tr>
    @endforeach
</table>
<br />
<div style="text-align: center;">
    @include('admin.question.pagination', ['paginator' => $questions, 'currentPage' => $questions->getCurrentPage(), 'lastPage' => $questions->getLastPage()])
</div>
@endif
{{ Form::close() }}

@stop

src/app/views/admin/question/pre_comment.blade.php
<!DOCTYPE HTML>
<html lang="ja">
<head>
<meta name="robots" content="noindex, nofollow" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="format-detection" content="telephone=no,address=no,email=no" />
<meta name="description" content="" />
<link href="{{ url('common/admin/css/reset.css') }}" type="text/css" rel="stylesheet"/>
<link href="{{ url('common/admin/css/common.css') }}" type="text/css" rel="stylesheet"/>
<link rel="stylesheet" href="{{ url('common/admin/css/jquery-ui-1.8.23.custom.css') }}" type="text/css" />
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>


<title>みんなの声管理画面モック</title>

<script type="text/javascript">
$(window).load(function(){
    
    $('div').html(window.opener.$('.result_comment').val());
});
</script>
<style>
ul li{
    margin:10px 0px;
}
</style>
</head>
<body>
<div style="margin:20px;">

</div>
</body>
</html>